# scripts/rename-brand.ps1
# =============================================================
# Batch-rename "education-advisor" → "education-advisor" across the
# source tree, skipping historical documents, dev tools, and
# the npm lockfile (which would be regenerated by `npm ci`).
# =============================================================

$root = 'C:\Users\sq199\.qwenpaw\workspaces\default\coding_projects\1\education-advisor'

# Patterns to replace: longest first to avoid double-replacement.
$replacements = @(
  @{ From = 'Education Advisor'; To = 'Education Advisor' }
  @{ From = 'Education Advisor';         To = 'Education Advisor' }
  @{ From = 'education-advisor';         To = 'education-advisor' }
  @{ From = 'EDUCATION_ADVISOR';         To = 'EDUCATION_ADVISOR' }
  @{ From = 'education_advisor';         To = 'education_advisor' }
)

# Skip these (historical, generated, or tools that pre-date the rename).
$skip = @(
  'package-lock.json'
  'BUG_REPORT.md'
  'SETTINGS_V2_REPORT.md'
  'SETTINGS_V3_REPORT.md'
  'SETTINGS_V4_FINAL_REPORT.md'
  'ZERO_BUG_ACCEPTANCE_REPORT.md'
  'SWARM_ARCHITECTURE.md'
  'supplement-task-plan-2026-06-03.md'
  'analyze_links.py'
  'link_chain.py'
  '示例学生_档案.md'
)

# Files we already manually edited and want to verify.
$alreadyDone = @(
  'package.json'
  'electron-builder.yml'
)

$utf8 = New-Object System.Text.UTF8Encoding($false)
$total = 0
$files = Get-ChildItem -Path $root -Recurse -File -Force |
  Where-Object { $_.FullName -notmatch '\\node_modules\\|\\\.git\\|\\dist\\|\\release\\|\.tmp-' } |
  Where-Object { $skip -notcontains $_.Name }

foreach ($f in $files) {
  $orig = [System.IO.File]::ReadAllText($f.FullName)
  $new = $orig
  $hits = 0
  foreach ($r in $replacements) {
    $before = $new
    $new = $new.Replace($r.From, $r.To)
    $diff = ($new.Length - $before.Length) / [Math]::Max(($r.To.Length - $r.From.Length), 1)
    $count = ([regex]::Matches($before, [regex]::Escape($r.From))).Count
    $hits += $count
  }
  if ($hits -gt 0 -and $new -ne $orig) {
    [System.IO.File]::WriteAllText($f.FullName, $new, $utf8)
    Write-Host ("  {0,-60}  {1,4} hits" -f $f.Name, $hits)
    $total += $hits
  }
}

Write-Host ""
Write-Host "Total replacements: $total"
